lucky_numbers = [5, 2, 17, 7, 99, 54]
friends = ["Maximilian", "George", "Samuel", "Christopher", "Tim"]
friends2 = friends.copy()
print("Array of friends: " + str(friends))
friends.insert(0, "Kevin")
print("Array of friends after adding a person at position 0 with insert: " + str(friends))
friends.append("Charles")
print("Array of friends after adding a person with append" + str(friends))
friends.pop()
print("Array of friends after deleting a person with pop" + str(friends))
print("Position where Kevin is in the Array: " + str(friends.index("Kevin")))
friends.remove(friends[0])
print("Array of friends after removing a person at position 0: " + str(friends))
# print(friends.index("Mike"))
lucky_numbers.reverse()
print("Array of numbers by reversed order: " + str(lucky_numbers))
friends.reverse()
print("Array of friends by reversed order: " + str(friends))
lucky_numbers.sort()
print("Sorted numbers Array: " + str(lucky_numbers))
friends.sort()
print("Sorted String Array: " + str(friends))
print("Copy of the original friends Array: " + str(friends2))
