import numpy as np

red = np.array([255, 0, 0])
green = np.array([0, 255, 0])
blue = np.array([0, 0, 255])

available_colors1 = np.array([red, green, blue])
available_colors2 = np.array([[120, 255, 3], [144, 20, 0], [24, 3, 61]])
searched_color1 = np.array([0, 0, 0])
searched_color2 = np.array([255, 255, 255])
searched_color3 = np.array([124, 56, 70])
searched_color4 = np.array([0, 255, 70])

X = np.linalg.solve(available_colors1, searched_color1)
print("Color 1 with available colors 1:", X)
X = np.linalg.solve(available_colors2, searched_color1)
print("Color 1 with available colors 2:", X)
print()
X = np.linalg.solve(available_colors1, searched_color2)
print("Color 2 with available colors 1:", X)
X = np.linalg.solve(available_colors2, searched_color2)
print("Color 2 with available colors 2:", X)
print()
X = np.linalg.solve(available_colors1, searched_color3)
print("Color 3 with available colors 1:", X)
X = np.linalg.solve(available_colors2, searched_color3)
print("Color 3 with available colors 2:", X)
print()
X = np.linalg.solve(available_colors1, searched_color4)
print("Color 4 with available colors 1:", X)
X = np.linalg.solve(available_colors2, searched_color4)
print("Color 4 with available colors 2:", X)
